<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Engram.Worker-1d54f841-9bff-4be0-91be-5e26477a801b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engram.Application\Engram.Application.csproj" />
    <ProjectReference Include="..\Engram.Infrastructure\Engram.Infrastructure.csproj" />
  </ItemGroup>
</Project>
